# Generated by Django 5.0.4 on 2024-04-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
